sudo: required
dist: trusty
language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install flake8 coverage
script:
- flake8 pynormalize --ignore=E402,E501,E731,E741
- coverage run --source=pynormalize --omit=pynormalize/version.py -m pytest -s tests/
after_success:
- coverage report -m
- if [ ${TRAVIS_PYTHON_VERSION} = "3.6" ]; then bash <(curl -s https://codecov.io/bash);
  fi
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: giannis.terzopoulos
  password:
    secure: 05mMhKmNxfhCaxdIeCa5gyZO3MgwljovZHzCHK8bQvTjQdMw7F4XGhibz8Io+656y+ciGjB8RjQdAqQlaCJhXWHuYWsgsXpaw08mSHPH/ocxrim+zlzL5EooEfd04clknvtVgbJTSWtZm8taMaSBrTg8TJ4d3sEu24VXtjTP9SQKNU7QOfJ1dJ+p4Vev6mnqCdqm1iXmu8xKNt14SXuhkEVU8DqzknC4zrMynn1N4a6Qy29IclmhH1MbAX5VqsXeCc6n/xiGCvnxo264DmQ0nBd+YM5dvKxOROjjVCxCFLKI4/7TeK64YhH7pgL87IQ9MJmMPsUE4fh+Ah4himT5gqvcjfR1RXheBqOkAnK+YqSqjKx4wHC4jDvlOvlcZPyipWQ8iysHXfczu+mfQXABR2Ww+MAuhJoVJsjp/sJTMNwbbpwhk98wab3QtKeuSuGI4ywRrXfFcxZ4OufmLG1hot46jIjPjZDf5Vvd+iFWjhfepT72Hu68+/FmV383QyUi5cAZNmw8XNgHj/LuUNltjZHnJ/YnvgOK8uPcif9cvaFlFc7illNEsZSGNryqv1T3qv+ljZIsn6Z7OqreWL2/xxhKvWQ8OztNbAS78CqTsgl9V3mGrn5q7n44kLimVKc0LZOiHv/3SZrDrsicJeBYB48mZXVj/cgkdGoBdcanUuY=
  on:
    tags: true
    repo: giannisterzopoulos/pynormalize
    branch: master
    python: 3.6
notifications:
  on_failure: always
  on_success: never
